services:
  orgaapp-db:
    image: mysql
    container_name: orgaapp-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: orgaapp
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: orgaapp
      MYSQL_PASSWORD: orgaapp