/**
 * Application initialization states
 */
export enum AppStateType {
	ERROR = 'ERROR',
	INITIALIZING_AUTH = 'INITIALIZING_AUTH',
	INITIALIZING_CORE = 'INITIALIZING_CORE',
	INITIALIZING_USER_DATA = 'INITIALIZING_USER_DATA',
	READY = 'READY',
	UNINITIALIZED = 'UNINITIALIZED'
}
