spring.application.name=orgaapp-backend
spring.datasource.url=jdbc:mysql://localhost:3306/orgaapp?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=orgaapp
spring.datasource.password=orgaapp

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

orgaapp.app.jwtSecret = cf8b2b587e830bc35c0c61a8035bf5c78b80d962363520cdf3caeba3cb42c830
orgaapp.app.jwtExpirationMs=7776000000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=something@gmail.com
spring.mail.password=test
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true