name: Run on Commit

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Maven Verify
        run: |
          ./backend-parent/mvnw -f backend-parent/pom.xml -B clean verify

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Verify mobileapp
        run: |
          npm -g install pnpm 
          pnpm install --prefix mobileapp --frozen-lockfile
          pnpm --prefix mobileapp sync-ionic-types
          pnpm --prefix mobileapp indexing
          pnpm --prefix mobileapp validate
          pnpm --prefix mobileapp test

      - name: Dump Docker container logs
        if: failure()
        run: |
          docker ps -a
          docker logs $(docker ps -q --filter ancestor=mysql) || true
