name: Run on Commit

on:
  push:
    branches:
      - main  # Change this to your target branch

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_DATABASE: kollapp
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: kollapp
          MYSQL_PASSWORD: kollapp
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Maven Verify
      run: mvn -B verify --file pom.xml
